#!/bin/sh
#
# example start stop daemon for CentOS (sysvinit)
#
# chkconfig: - 64 36
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 2 3 4 6
# Required-Start:
# description: java-app start stop daemon for CentOS
# processname: java-app
# pidfile: none
# lockfile: /var/lock/subsys/java-app

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

USER="root"
APPNAME="tinode"
APPBIN="$GOPATH/bin/server"
CONFIG="$GOPATH/src/github.com/mudphilo/chat/server/tinode.conf"
DATA="$GOPATH/tinode-web/"
APPARGS="-config=$CONFIG -static_data=$DATA"
LOGFILE="/var/log/$APPNAME/error.log"
LOCKFILE="/var/lock/subsys/$APPNAME"

LOGPATH=$(dirname $LOGFILE)

start() {
  [ -x $prog ] || exit 5
  [ -d $LOGPATH ] || mkdir $LOGPATH
  [ -f $LOGFILE ] || touch $LOGFILE

  echo -n $"Starting $APPNAME: "
  #daemon --user=$USER "$APPBIN $APPARGS >/dev/null "
  daemon --user=$USER "$APPBIN $APPARGS >/dev/null 2>&1"
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch $LOCKFILE
  return $RETVAL
}

stop() {
  echo -n $"Stopping $APPNAME: "
  killproc $APPBIN
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
  return $RETVAL
}

restart() {
  stop
  start
}

rh_status() {
  status $prog
}

rh_status_q() {
  rh_status >/dev/null 2>&1
}

case "$1" in
    start)
    rh_status_q && exit 0
    $1
  ;;
    stop)
    rh_status_q || exit 0
    $1
  ;;
    restart)
    $1
  ;;
    status)
    rh_status
  ;;
    *)
  echo $"Usage: $0 {start|stop|status|restart}"
  exit 2
esac